---
- name: restart blackbox_exporter
  systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: restarted
  become: true
  tags: blackbox_exporter

- name: reload blackbox_exporter
  systemd:
    name: blackbox_exporter
    state: reloaded
  become: true
  tags: blackbox_exporter

- name: reload ufw
  systemd:
    name: ufw
    state: reloaded
  tags: blackbox_exporter
  become: true

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
  tags: blackbox_exporter
  become: true